'use client';
import{useEffect,useMemo,useState}from'react';
import{getSupabase,friendlyError}from'../../lib/supabase';
import{Search,TicketCheck,Users,Trophy,Gift,RotateCw,LogOut,X,Plus,Phone,ChevronLeft}from'lucide-react';

export default function AdminPage(){
 const[ready,setReady]=useState(false),[allowed,setAllowed]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[stats,setStats]=useState({users:0,spins:0,prizes:0}),[users,setUsers]=useState([]),[codes,setCodes]=useState([]),[query,setQuery]=useState(''),[tab,setTab]=useState('customers'),[selected,setSelected]=useState(null),[addAttempts,setAddAttempts]=useState('1'),[codeInput,setCodeInput]=useState(''),[codeCheck,setCodeCheck]=useState(null),[leaders,setLeaders]=useState([]);
 const load=async()=>{const sb=getSupabase(),{data:{user}}=await sb.auth.getUser();if(!user){setReady(true);return}const{data:a}=await sb.from('admin_users').select('role').eq('user_id',user.id).maybeSingle();if(!a){setReady(true);setAllowed(false);return}setAllowed(true);const[{count:u},{count:s},{count:p},{data:profiles},{data:redemptions},{data:lb}]=await Promise.all([sb.from('profiles').select('*',{count:'exact',head:true}),sb.from('spin_results').select('*',{count:'exact',head:true}),sb.from('prizes').select('*',{count:'exact',head:true}),sb.from('profiles').select('id,full_name,phone,created_at,game_wallets(points,attempts),prizes(id,title,prize_type,created_at,redemption_codes(id,code,status,redeemed_at))').order('created_at',{ascending:false}).limit(500),sb.from('redemption_codes').select('id,code,status,created_at,redeemed_at,prizes(title),profiles(full_name,phone)').order('created_at',{ascending:false}).limit(200),sb.rpc('get_leaderboard',{result_limit:100})]);setStats({users:u||0,spins:s||0,prizes:p||0});setUsers(profiles||[]);setCodes(redemptions||[]);setLeaders(lb||[]);setReady(true)};
 useEffect(()=>{load()},[]);
 const login=async()=>{setError('');const{error:e}=await getSupabase().auth.signInWithPassword({email:email.trim().toLowerCase(),password});if(e){setError('البريد الإلكتروني أو كلمة المرور غير صحيحة');return}setReady(false);await load()};
 const redeem=async code=>{const{error:e}=await getSupabase().rpc('redeem_prize',{input_code:code});if(e){setCodeCheck({valid:false,message:friendlyError(e)});return}setCodeCheck({...codeCheck,valid:false,status:'redeemed',message:'تم استلام الجائزة واستبدال الكود بنجاح.'});await load()};
 const validateCode=async()=>{if(!codeInput.trim())return;const{data,error:e}=await getSupabase().rpc('admin_validate_redemption',{input_code:codeInput.trim()});setCodeCheck(e?{valid:false,message:friendlyError(e)}:data)};
 const addMoreAttempts=async()=>{const amount=Number(addAttempts);if(!selected||!Number.isInteger(amount)||amount<1)return;const{data,error:e}=await getSupabase().rpc('admin_add_attempts',{target_user:selected.id,amount});if(e){alert(friendlyError(e));return}setSelected(v=>({...v,game_wallets:{...v.game_wallets,attempts:data}}));setUsers(v=>v.map(x=>x.id===selected.id?{...x,game_wallets:{...x.game_wallets,attempts:data}}:x));setAddAttempts('1')};
 const filtered=useMemo(()=>users.filter(u=>!query||[u.full_name,u.phone].some(v=>String(v||'').includes(query))),[users,query]);
 if(!ready)return <main className="adminLoading">جاري التحميل…</main>;
 if(!allowed)return <main className="adminLogin" dir="rtl"><section><div className="adminBrand">أثل <small>ADMIN</small></div><h1>لوحة الإدارة</h1><p>الدخول مخصص لفريق أثل.</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="البريد الإلكتروني" dir="ltr" type="email"/><input value={password} onChange={e=>setPassword(e.target.value)} placeholder="كلمة المرور" dir="ltr" type="password" onKeyDown={e=>e.key==='Enter'&&login()}/>{error&&<div className="formError">{error}</div>}<button onClick={login}>دخول</button></section></main>;
 return <main className="adminApp" dir="rtl"><header><div><b>أثل</b><small>لوحة الإدارة</small></div><button onClick={async()=>{await getSupabase().auth.signOut();location.reload()}}><LogOut/></button></header>
 <nav className="adminTabs"><button className={tab==='customers'?'active':''} onClick={()=>setTab('customers')}><Users/> العملاء</button><button className={tab==='ranking'?'active':''} onClick={()=>setTab('ranking')}><Trophy/> الترتيب</button></nav>
 <section className="adminStats"><article><Users/><span>العملاء</span><b>{stats.users}</b></article><article><RotateCw/><span>الدورات</span><b>{stats.spins}</b></article><article><Gift/><span>الجوائز</span><b>{stats.prizes}</b></article></section>
 {tab==='customers'?<><section className="adminPanel"><div className="adminPanelTitle"><div><small>العملاء</small><h2>حسابات المشاركين</h2></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث بالاسم أو الرقم"/></label></div><div className="adminTable customerRows">{filtered.map(u=><article key={u.id} onClick={()=>{setSelected(u);setCodeCheck(null);setCodeInput('')}}><div><b>{u.full_name||'بدون اسم'}</b><small dir="ltr">{u.phone||'—'}</small></div><span><Trophy/> {u.game_wallets?.points||0}</span><span>{u.game_wallets?.attempts||0} محاولة</span><ChevronLeft/></article>)}</div></section>
 <section className="adminPanel"><div className="adminPanelTitle"><div><small>الاستبدال السريع</small><h2>التحقق من كود جائزة</h2></div></div><div className="redeemCheck"><input value={codeInput} onChange={e=>setCodeInput(e.target.value.replace(/\D/g,''))} placeholder="أدخل كود الجائزة" inputMode="numeric" dir="ltr"/><button onClick={validateCode}><Search/> تحقق</button></div>{codeCheck&&<div className={'codeResult '+(codeCheck.valid?'valid':'invalid')}><b>{codeCheck.valid?'الكود صالح للاستبدال':codeCheck.status==='redeemed'?'تم استخدام الكود':'الكود غير صالح'}</b><span>{codeCheck.title||codeCheck.message||''}</span>{codeCheck.valid&&<><small>{codeCheck.full_name} · {codeCheck.phone}</small><div className="redeemActions"><button className="laterBtn" onClick={()=>setCodeCheck(null)}>إلغاء، الاستلام لاحقًا</button><button onClick={()=>redeem(codeCheck.code)}><TicketCheck/> تم استلام الجائزة</button></div></>}</div>}</section></>:<section className="adminPanel"><div className="adminPanelTitle"><div><small>المسابقة</small><h2>أفضل 100</h2></div></div><div className="adminRanking">{Array.from({length:100},(_,i)=>leaders[i]||{rank:i+1,display_name:'***',points:null}).map((x,i)=><div key={i} className={i<10?'top':''}><b>#{x.rank}</b><span>{x.display_name||'***'}</span><strong>{x.points??'***'}</strong></div>)}</div></section>}
 {selected&&<div className="adminModalBackdrop" onClick={()=>setSelected(null)}><section className="customerModal" onClick={e=>e.stopPropagation()}><button className="adminModalClose" onClick={()=>setSelected(null)}><X/></button><div className="customerHead"><div className="customerAvatar"><Users/></div><div><small>بيانات العميل</small><h2>{selected.full_name||'بدون اسم'}</h2><p dir="ltr"><Phone/> {selected.phone||'—'}</p></div></div><div className="customerStats"><div><small>النقاط</small><b>{selected.game_wallets?.points||0}</b></div><div><small>المحاولات</small><b>{selected.game_wallets?.attempts||0}</b></div></div><div className="attemptAdder"><div><small>إضافة محاولات</small><p>تضاف مباشرة إلى رصيد العميل.</p></div><input value={addAttempts} onChange={e=>setAddAttempts(e.target.value.replace(/\D/g,''))} inputMode="numeric"/><button onClick={addMoreAttempts}><Plus/> إضافة</button></div><h3>الجوائز التي فاز بها</h3><div className="customerPrizes">{selected.prizes?.length?selected.prizes.map(p=>{const rc=p.redemption_codes?.[0];return <div key={p.id}><span><Gift/><b>{p.title}</b><small>{p.prize_type}</small></span><code>{rc?.code||'—'}</code><em className={rc?.status==='redeemed'?'used':''}>{rc?.status==='redeemed'?'تم الاستبدال':'متاح'}</em></div>}):<p className="emptyAdmin">لم يفز بجوائز حتى الآن.</p>}</div></section></div>}
 </main>}