'use client';
import{useEffect,useState}from'react';
import{getSupabase,normalizeSaudiPhone,friendlyError}from'../../lib/supabase';
import{Search,TicketCheck,Users,Trophy,Gift,RotateCw,LogOut}from'lucide-react';

export default function AdminPage(){const[ready,setReady]=useState(false),[allowed,setAllowed]=useState(false),[phone,setPhone]=useState(''),[otp,setOtp]=useState(''),[step,setStep]=useState('phone'),[error,setError]=useState(''),[stats,setStats]=useState({users:0,spins:0,prizes:0}),[users,setUsers]=useState([]),[codes,setCodes]=useState([]),[query,setQuery]=useState('');
 const load=async()=>{const sb=getSupabase(),{data:{user}}=await sb.auth.getUser();if(!user){setReady(true);return}const{data:a}=await sb.from('admin_users').select('role').eq('user_id',user.id).maybeSingle();if(!a){setReady(true);setAllowed(false);return}setAllowed(true);const[{count:u},{count:s},{count:p},{data:profiles},{data:redemptions}]=await Promise.all([sb.from('profiles').select('*',{count:'exact',head:true}),sb.from('spin_results').select('*',{count:'exact',head:true}),sb.from('prizes').select('*',{count:'exact',head:true}),sb.from('profiles').select('id,full_name,phone,created_at,game_wallets(points,attempts)').order('created_at',{ascending:false}).limit(100),sb.from('redemption_codes').select('id,code,status,created_at,prizes(title),profiles(full_name,phone)').order('created_at',{ascending:false}).limit(100)]);setStats({users:u||0,spins:s||0,prizes:p||0});setUsers(profiles||[]);setCodes(redemptions||[]);setReady(true)};
 useEffect(()=>{load()},[]);
 const send=async()=>{const p=normalizeSaudiPhone(phone);if(!p){setError('رقم الجوال غير صحيح');return}const{error:e}=await getSupabase().auth.signInWithOtp({phone:p});if(e)setError(friendlyError(e));else{setPhone(p);setStep('otp')}};
 const verify=async()=>{const{error:e}=await getSupabase().auth.verifyOtp({phone,token:otp,type:'sms'});if(e)setError(friendlyError(e));else{setReady(false);await load()}};
 const redeem=async code=>{if(!confirm(`تأكيد استبدال الكود ${code}؟ لا يمكن استخدامه مرة أخرى.`))return;const{error:e}=await getSupabase().rpc('redeem_prize',{input_code:code});if(e)alert(friendlyError(e));else load()};
 const filtered=users.filter(u=>!query||[u.full_name,u.phone].some(v=>String(v||'').includes(query)));
 if(!ready)return <main className="adminLoading">جاري التحميل…</main>;
 if(!allowed)return <main className="adminLogin" dir="rtl"><section><div className="adminBrand">أثل <small>ADMIN</small></div><h1>لوحة الإدارة</h1><p>الدخول مخصص لفريق أثل.</p>{step==='phone'?<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="05XXXXXXXX" dir="ltr"/>:<input value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,''))} placeholder="رمز التحقق" dir="ltr" inputMode="numeric"/>}{error&&<div className="formError">{error}</div>}<button onClick={step==='phone'?send:verify}>{step==='phone'?'إرسال الرمز':'دخول'}</button></section></main>;
 return <main className="adminApp" dir="rtl"><header><div><b>أثل</b><small>لوحة الإدارة</small></div><button onClick={async()=>{await getSupabase().auth.signOut();location.reload()}}><LogOut/></button></header><section className="adminStats"><article><Users/><span>الحسابات</span><b>{stats.users}</b></article><article><RotateCw/><span>الدورات</span><b>{stats.spins}</b></article><article><Gift/><span>الجوائز</span><b>{stats.prizes}</b></article></section><section className="adminPanel"><div className="adminPanelTitle"><div><small>المشاركون</small><h2>الحسابات والنقاط</h2></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="بحث بالاسم أو الرقم"/></label></div><div className="adminTable">{filtered.map(u=><article key={u.id}><div><b>{u.full_name||'بدون اسم'}</b><small dir="ltr">{u.phone||'—'}</small></div><span><Trophy/> {u.game_wallets?.points||0}</span><span>{u.game_wallets?.attempts||0} محاولة</span></article>)}</div></section><section className="adminPanel"><div className="adminPanelTitle"><div><small>الاستبدال</small><h2>أكواد الجوائز</h2></div></div><div className="adminTable">{codes.map(c=><article key={c.id}><div><b>{c.prizes?.title||'جائزة'}</b><small>{c.profiles?.full_name||c.profiles?.phone||'مشارك'}</small></div><code>{c.code}</code><button disabled={c.status!=='available'} onClick={()=>redeem(c.code)}><TicketCheck/>{c.status==='available'?'استبدال':'مستخدم'}</button></article>)}</div></section></main>}