'use client';
import React,{useMemo,useState}from'react';
import{Coffee,Gift,RotateCw,Trophy,UserRound,Share2,X,Copy,TicketCheck}from'lucide-react';

const SEGMENTS=[{type:'points',value:10},{type:'points',value:20},{type:'coffee'},{type:'points',value:30},{type:'points',value:50},{type:'points',value:100},{type:'points',value:20},{type:'harvest'},{type:'points',value:200},{type:'points',value:50}];
const STEP=36, OFFSET=18;
const leaders=[['HUS****',620],['ABD****',570],['SAR****',490],['MOH****',430],['FAI****',390]];
const code=()=>('ATHL-'+Math.random().toString(36).slice(2,8)).toUpperCase();
function Brand(){return <div className="brand"><b>أثل</b><small>ATHL ROASTERY</small></div>}
function Wheel({rotation=0}){return <div className="wheelShell"><div className="wheelPointer"/><div className="prizeWheel" style={{transform:`rotate(${rotation}deg)`}}><div className="wheelColor"/>{SEGMENTS.map((s,i)=><div className="wheelSlice" key={i} style={{'--angle':`${i*STEP+OFFSET}deg`}}><span className={'sliceContent '+s.type}>{s.type==='coffee'?<><span className="coffeeBadge"><Coffee/></span><small>كوب</small></>:s.type==='harvest'?<><Gift/><small>محصول</small></>:<><b>{s.value}</b><small>نقطة</small></>}</span></div>)}<div className="wheelHub"><span>أ</span></div></div></div>}
export default function AthalGame(){
 const[panel,setPanel]=useState(null),[tries,setTries]=useState(3),[total,setTotal]=useState(0),[rotation,setRotation]=useState(0),[spinning,setSpinning]=useState(false),[result,setResult]=useState(null),[prizes,setPrizes]=useState([]),[win,setWin]=useState(null),[refInput,setRefInput]=useState('');
 const referral=useMemo(()=>code(),[]),rank=1+leaders.filter(x=>x[1]>total).length,coffee=prizes.filter(p=>p.type==='coffee').length,harvest=prizes.filter(p=>p.type==='harvest').length;
 const spin=()=>{if(spinning||tries<=0)return;setResult(null);setSpinning(true);const index=Math.floor(Math.random()*SEGMENTS.length),segment=SEGMENTS[index],current=((rotation%360)+360)%360,target=(360-(index*STEP+OFFSET)+360)%360,delta=(target-current+360)%360;setRotation(rotation+2160+delta);setTimeout(()=>{setSpinning(false);setTries(v=>v-1);setResult(segment);if(segment.type==='points')setTotal(v=>v+segment.value);else{const prize={id:Date.now(),type:segment.type,label:segment.type==='coffee'?'كوب قهوة':'محصول أثل',code:code(),used:false};setPrizes(v=>[prize,...v]);setWin(prize)}navigator.vibrate?.([25,30,60])},4200)};
 const share=async()=>{const text=`جرّب عجلة أثل واستخدم كودي ${referral}`;try{if(navigator.share)await navigator.share({title:'تحدي أثل',text,url:location.href});else await navigator.clipboard.writeText(`${text} ${location.href}`)}catch{}};
 const applyReferral=()=>{const v=refInput.trim().toUpperCase();if(v&&v!==referral){setRefInput('');alert('تم قبول الكود. في النسخة المرتبطة بالسيرفر تُضاف محاولتان لصاحب الكود بعد تحقق التسجيل.')}};
 return <main className="athlApp" dir="rtl"><div className="floatingActions"><button className="scoreAction" onClick={()=>setPanel('leaders')}><Trophy/><span><small>النقاط</small><b>{total}</b></span><i>#{rank}</i></button><button className="accountAction" onClick={()=>setPanel('account')}><UserRound/></button></div><section className="wheelPage"><Brand/><div className="intro"><h1>لف واربح</h1><p>اجمع النقاط، وقد تربح كوب قهوة أو محصولًا من أثل.</p></div><Wheel rotation={rotation}/><div className="resultArea">{spinning?<span>العجلة تدور...</span>:result?.type==='points'?<><small>أضيفت إلى مجموعك</small><strong>+{result.value} نقطة</strong></>:<><small>المحاولات المتاحة</small><strong>{tries}</strong></>}</div><button className="spinButton" disabled={spinning||tries<=0} onClick={spin}>{spinning?<><RotateCw className="spinIcon"/> جاري الدوران</>:tries>0?<><RotateCw/> لف العجلة</>:'انتهت المحاولات'}</button><div className="prizeSummary"><span><Coffee/><b>{coffee}</b> كوب</span><i/><span><Gift/><b>{harvest}</b> محصول</span></div></section>
 {panel&&<div className="sheetBackdrop" onClick={()=>setPanel(null)}><section className="bottomSheet" onClick={e=>e.stopPropagation()}><div className="sheetGrab"/><button className="sheetClose" onClick={()=>setPanel(null)}><X/></button>{panel==='leaders'?<><div className="sheetTitle"><Trophy/><div><small>المسابقة</small><h2>الترتيب</h2></div></div><div className="leaderList">{leaders.map((x,i)=><div key={x[0]}><b>#{i+1}</b><span>{x[0]}</span><strong>{x[1]}</strong></div>)}<div className="myRow"><b>#{rank}</b><span>أنت</span><strong>{total}</strong></div></div></>:<><div className="sheetTitle"><UserRound/><div><small>أثل</small><h2>حسابي</h2></div></div><div className="accountStats"><div><small>النقاط</small><strong>{total}</strong></div><div><small>المحاولات</small><strong>{tries}</strong></div></div><h3 className="miniTitle">جوائز الاستبدال</h3><div className="voucherList">{prizes.length?prizes.map(p=><div key={p.id}><span>{p.type==='coffee'?<Coffee/>:<Gift/>}<b>{p.label}</b></span><code>{p.code}</code><em>{p.used?'مستخدم':'متاح'}</em></div>):<p>لا توجد جوائز حتى الآن</p>}</div><h3 className="miniTitle">دعوة صديق</h3><div className="refCode"><code>{referral}</code><button onClick={()=>navigator.clipboard?.writeText(referral)}><Copy/></button></div><button className="shareButton" onClick={share}><Share2/> مشاركة الرابط والكود</button><div className="refInput"><input value={refInput} onChange={e=>setRefInput(e.target.value)} placeholder="أدخل كود دعوة"/><button onClick={applyReferral}>استخدام</button></div><small className="refNote">عند ربط الحسابات: تسجيل شخص جديد بكودك يمنحك محاولتين إضافيتين.</small></>}</section></div>}
 {win&&<div className="winBackdrop"><section className="winModal"><div className="winIcon">{win.type==='coffee'?<Coffee/>:<Gift/>}</div><small>مبروك!</small><h2>فزت بـ{win.label}</h2><p>احتفظ بالكود وقدمه عند الاستبدال. يستخدم مرة واحدة فقط.</p><code>{win.code}</code><button onClick={()=>{navigator.clipboard?.writeText(win.code);setWin(null)}}><TicketCheck/> حفظ الكود وإغلاق</button></section></div>}
 </main>
}