'use client';
import React,{useCallback,useEffect,useRef,useState}from'react';
import dynamic from'next/dynamic';
import{Trophy,UserRound,Share2,Coffee,X,Play,Gift,Pause}from'lucide-react';
import{pointsFor,comboBonus,multiplier}from'../lib/game/config';
import{createPattern}from'../lib/game/patterns';
const RunnerScene=dynamic(()=>import('./RunnerScene'),{ssr:false});
const leaders=[['HA','HUS****',486],['AA','ABD****',459],['SA','SAR****',431],['MA','MOH****',407],['FA','FAI****',389],['RA','RAM****',371]];
function Logo(){return <div className="athalLogo"><span>أثل</span><small>ATHL</small></div>}
export default function App(){
 const[registered,setRegistered]=useState(false),[phone,setPhone]=useState(''),[name,setName]=useState(''),[authStep,setAuthStep]=useState('details'),[otp,setOtp]=useState(['','','','']),[needsAuth,setNeedsAuth]=useState(false),[tab,setTab]=useState('game'),[tries,setTries]=useState(3),[total,setTotal]=useState(0),[round,setRound]=useState(0),[playing,setPlaying]=useState(false),[lane,setLane]=useState(1),[jump,setJump]=useState(false),[slide,setSlide]=useState(false),[objects,setObjects]=useState([]),[speed,setSpeed]=useState(.16),[combo,setCombo]=useState(0),[last,setLast]=useState(null),[paused,setPaused]=useState(false),[elevated,setElevated]=useState(false);
 const touch=useRef(null),id=useRef(0),wave=useRef(0),rank=1+leaders.filter(x=>x[2]>total).length;
 const end=useCallback(()=>{setPlaying(false);setTotal(v=>v+round);setLast(round);setTries(v=>Math.max(0,v-1));setObjects([]);if(!registered)setNeedsAuth(true)},[round,registered]);
 useEffect(()=>{if(!playing||paused)return;const spawn=setInterval(()=>{const difficulty=Math.min(3,Math.floor(wave.current/6));const spawn=createPattern(id.current,difficulty);id.current=spawn.lastId;wave.current++;setObjects(a=>[...a,...spawn.batch])},700);const move=setInterval(()=>setObjects(a=>{const n=[];for(const o of a){const q={...o,depth:o.depth-speed};if(q.depth<2.9&&q.depth>1.5&&q.lane===lane){if(q.type==='platform'){if(jump||elevated){setElevated(true);continue}else{setCombo(0);end();return []}}else if(q.type==='barrier'){if(!jump){setCombo(0);end();return []}}else if(q.type==='highbar'){if(!slide){setCombo(0);end();return []}}else if(q.type==='train'){setCombo(0);end();return []}else{if((q.type==='roofCoffee'||q.type==='roofCake')&&!elevated){if(q.depth>-3)n.push(q);continue}const pts=pointsFor(q.type);setRound(s=>s+pts+comboBonus(combo));setCombo(c=>c+1);continue}}if(q.depth>-3)n.push(q)}return n}),32);const harder=setInterval(()=>setSpeed(s=>Math.min(.34,s+.012)),4500);return()=>{clearInterval(spawn);clearInterval(move);clearInterval(harder)}},[playing,paused,lane,jump,slide,speed,combo,elevated,end]);
 const start=()=>{if(!tries||(!registered&&last!==null))return;setRound(0);setCombo(0);setLane(1);setElevated(false);wave.current=0;setSpeed(.16);setObjects([]);setLast(null);setPlaying(true)};
 const swipeEnd=e=>{if(!touch.current||!playing)return;const p=e.changedTouches?.[0]||e;const dx=p.clientX-touch.current.x,dy=p.clientY-touch.current.y;if(Math.abs(dx)>Math.abs(dy)&&Math.abs(dx)>28)setLane(l=>Math.max(0,Math.min(2,l+(dx>0?1:-1))));else if(dy<-28){setJump(true);setTimeout(()=>setJump(false),650);if(elevated)setTimeout(()=>setElevated(false),900)}else if(dy>28){setSlide(true);setTimeout(()=>setSlide(false),600)}touch.current=null};
 const share=async()=>{const url=location.origin+'?ref=ATHL24';try{if(navigator.share)await navigator.share({title:'تحدي افتتاح أثل',text:'تقدر تتجاوز نتيجتي؟',url});else await navigator.clipboard.writeText(url)}catch{}};
 return <main className="runnerApp"><div className="runnerWorld" onTouchStart={e=>{const p=e.touches[0];touch.current={x:p.clientX,y:p.clientY}}} onTouchEnd={swipeEnd}><RunnerScene lane={lane} jump={jump} slide={slide} elevated={elevated} objects={objects} playing={playing&&!paused}/>
 <button className="pauseBtn" onClick={()=>playing&&setPaused(true)}><Pause/></button><div className="arcadeHud"><div className="scorePlate"><span>×{multiplier(combo)}</span><b>★</b><strong>{String(total+round).padStart(5,'0')}</strong></div><div className="tryPlate"><Coffee/><strong>{tries}</strong></div></div>
 <div className="runnerScore"><small>الجولة</small><b>{round}</b></div>
 <button className="shareOrb" onClick={share}><Share2/></button>
 {paused&&<div className="pauseMenu"><Logo/><h2>متوقف مؤقتًا</h2><button onClick={()=>setPaused(false)}><Play/> متابعة</button><button onClick={()=>{setPaused(false);setTab('leaders')}}><Trophy/> المتصدرون</button><button onClick={()=>{setPaused(false);setTab('account')}}><UserRound/> حسابي</button><button onClick={share}><Share2/> مشاركة</button></div>}
 {!playing&&tries>0&&!needsAuth&&<div className="runnerStart"><Logo/><h1>{last===null?'جاهز؟':'+'+last+' نقطة'}</h1><p>{last===null?'اسحب يمين ويسار، اقفز وتجنب العوائق.':'رصيدك الآن '+total+' · المركز #'+rank}</p><div className="collectLegend"><span>☕ +1</span><span>🍰 +3</span><span>بن +5</span></div><button onClick={start}><Play/> {last===null?'ابدأ الجري':'المحاولة التالية'}</button><small>↑ قفز　↓ انزلاق　← → تغيير المسار</small></div>}
 {!playing&&tries===0&&<div className="noTries"><Gift/><h2>انتهت محاولاتك</h2><b>{total} نقطة · المركز #{rank}</b><p>شارك رابطك، وعند تسجيل صديق جديد تحصل على محاولة إضافية.</p><button onClick={share}><Share2/> شارك التحدي</button></div>}</div>
 {needsAuth&&<div className="authGate"><div className="authCard"><Logo/>{authStep==='details'?<><span className="eventTag">احفظ نتيجتك</span><h2>سجّل للمنافسة</h2><p>سجّل الآن حتى نحفظ <b>{last}</b> نقطة ونضيفك للترتيب.</p><label>الاسم</label><input className="authInput" value={name} onChange={e=>setName(e.target.value)} placeholder="اسمك"/><label>رقم الجوال</label><div className="authPhone"><span>+966</span><input inputMode="numeric" maxLength="10" value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))} placeholder="5X XXX XXXX"/></div><button className="authPrimary" onClick={()=>name.trim().length>1&&phone.length>=9&&setAuthStep('otp')}>إرسال رمز التحقق</button></>:<><span className="eventTag">التحقق من الجوال</span><h2>أدخل رمز OTP</h2><p>أرسلنا رمزًا من 4 أرقام إلى <b dir="ltr">+966 {phone}</b></p><div className="otpRow" dir="ltr">{otp.map((v,i)=><input key={i} inputMode="numeric" maxLength="1" value={v} onChange={e=>{const n=[...otp],val=e.target.value.replace(/\D/g,'').slice(-1);n[i]=val;setOtp(n);if(val)e.target.nextElementSibling?.focus()}}/>)}</div><button className="authPrimary" onClick={()=>{if(otp.join('').length===4){setRegistered(true);setNeedsAuth(false);setAuthStep('details')}}}>تحقق وادخل المنافسة</button><button className="authBack" onClick={()=>setAuthStep('details')}>تعديل رقم الجوال</button><small>التحقق تجريبي حاليًا؛ سيتم ربط إرسال OTP الحقيقي بمزود الرسائل.</small></>}</div></div>}
 {tab==='leaders'&&<div className="panel"><button className="close" onClick={()=>setTab('game')}><X/></button><div className="panelTitle"><Trophy/><small>افتتاح أثل</small><h1>المتصدرون</h1><p>مجموع النقاط من جميع المحاولات</p></div><div className="topThree">{leaders.slice(0,3).map((x,i)=><div className={'place p'+(i+1)} key={x[1]}><b>{i+1}</b><span>{x[0]}</span><strong>{x[2]}</strong><small>نقطة</small></div>)}</div><div className="rankList">{leaders.slice(3).map((x,i)=><div key={x[1]}><b>{i+4}</b><span className="avatar">{x[0]}</span><strong>{x[1]}</strong><em>{x[2]}</em></div>)}</div><div className="myRank"><span>ترتيبك</span><b>#{rank}</b><strong>{total} نقطة</strong></div></div>}
 {tab==='account'&&<div className="panel"><button className="close" onClick={()=>setTab('game')}><X/></button><div className="accountSimple"><Logo/><h1>{name||'حسابك'}</h1><p dir="ltr">+966 {phone}</p><div><span><small>النقاط</small><b>{total}</b></span><span><small>المركز</small><b>#{rank}</b></span><span><small>المحاولات</small><b>{tries}</b></span></div><button onClick={share}><Share2/> مشاركة رابطك</button></div></div>}</main>
}