'use client';
import React,{useState}from'react';
import{Coffee,Gift,RotateCw,Trophy,UserRound,Share2,X}from'lucide-react';
const SEGMENTS=[{type:'points',value:10},{type:'points',value:20},{type:'coffee'},{type:'points',value:30},{type:'points',value:50},{type:'points',value:100},{type:'points',value:20},{type:'harvest'},{type:'points',value:200},{type:'points',value:50}];
const STEP=360/SEGMENTS.length;
const leaders=[['HUS****',620],['ABD****',570],['SAR****',490],['MOH****',430],['FAI****',390]];
function Brand(){return <div className="brand"><b>أثل</b><small>ATHL ROASTERY</small></div>}
function Wheel({rotation=0}){return <div className="wheelShell"><div className="wheelPointer"/><div className="prizeWheel" style={{transform:`rotate(${rotation}deg)`}}><div className="wheelColor"/>{SEGMENTS.map((s,i)=><div className="wheelSlice" key={i} style={{'--angle':`${i*STEP+STEP/2}deg`}}><span className={'sliceContent '+s.type}>{s.type==='coffee'?<><Coffee/><small>كوب</small></>:s.type==='harvest'?<><Gift/><small>محصول</small></>:<><b>{s.value}</b><small>نقطة</small></>}</span></div>)}<div className="wheelHub"><span>أ</span></div></div></div>}
export default function AthalGame(){
 const[panel,setPanel]=useState(null),[tries,setTries]=useState(3),[total,setTotal]=useState(0),[rotation,setRotation]=useState(0),[spinning,setSpinning]=useState(false),[result,setResult]=useState(null),[coffee,setCoffee]=useState(0),[harvest,setHarvest]=useState(0);
 const rank=1+leaders.filter(x=>x[1]>total).length;
 const spin=()=>{if(spinning||tries<=0)return;setResult(null);setSpinning(true);const index=Math.floor(Math.random()*SEGMENTS.length),segment=SEGMENTS[index],center=index*STEP+STEP/2,current=((rotation%360)+360)%360,target=(360-center+360)%360,delta=(target-current+360)%360;setRotation(rotation+2160+delta);setTimeout(()=>{setSpinning(false);setTries(v=>v-1);setResult(segment);if(segment.type==='points')setTotal(v=>v+segment.value);if(segment.type==='coffee')setCoffee(v=>v+1);if(segment.type==='harvest')setHarvest(v=>v+1);navigator.vibrate?.([25,30,60])},4200)};
 const share=async()=>{try{if(navigator.share)await navigator.share({title:'تحدي أثل',text:'جرّب عجلة أثل',url:location.href});else await navigator.clipboard.writeText(location.href)}catch{}};
 return <main className="athlApp" dir="rtl"><div className="floatingActions"><button className="scoreAction" onClick={()=>setPanel('leaders')}><Trophy/><span><small>النقاط</small><b>{total}</b></span><i>#{rank}</i></button><button className="accountAction" aria-label="الحساب" onClick={()=>setPanel('account')}><UserRound/></button></div><section className="wheelPage"><Brand/><div className="intro"><h1>لف واربح</h1><p>اجمع النقاط، وقد تربح كوب قهوة أو محصولًا من أثل.</p></div><Wheel rotation={rotation}/><div className="resultArea">{spinning?<span>العجلة تدور...</span>:result?result.type==='points'?<><small>أضيفت إلى مجموعك</small><strong>+{result.value} نقطة</strong></>:result.type==='coffee'?<><small>مبروك!</small><strong><Coffee/> فزت بكوب قهوة</strong></>:<><small>مبروك!</small><strong><Gift/> فزت بمحصول أثل</strong></>:<><small>المحاولات المتاحة</small><strong>{tries}</strong></>}</div><button className="spinButton" disabled={spinning||tries<=0} onClick={spin}>{spinning?<><RotateCw className="spinIcon"/> جاري الدوران</>:tries>0?<><RotateCw/> لف العجلة</>:'انتهت المحاولات'}</button><div className="prizeSummary"><span><Coffee/><b>{coffee}</b> كوب</span><i/><span><Gift/><b>{harvest}</b> محصول</span></div></section>{panel&&<div className="sheetBackdrop" onClick={()=>setPanel(null)}><section className="bottomSheet" onClick={e=>e.stopPropagation()}><div className="sheetGrab"/><button className="sheetClose" onClick={()=>setPanel(null)}><X/></button>{panel==='leaders'?<><div className="sheetTitle"><Trophy/><div><small>المسابقة</small><h2>الترتيب</h2></div></div><div className="leaderList">{leaders.map((x,i)=><div key={x[0]}><b>#{i+1}</b><span>{x[0]}</span><strong>{x[1]}</strong></div>)}<div className="myRow"><b>#{rank}</b><span>أنت</span><strong>{total}</strong></div></div></>:<><div className="sheetTitle"><UserRound/><div><small>أثل</small><h2>حسابي</h2></div></div><div className="accountStats"><div><small>النقاط</small><strong>{total}</strong></div><div><small>المحاولات</small><strong>{tries}</strong></div><div><small>أكواب</small><strong>{coffee}</strong></div><div><small>محاصيل</small><strong>{harvest}</strong></div></div><button className="shareButton" onClick={share}><Share2/> مشاركة التحدي</button></>}</section></div>}</main>
}