'use client';
import {Canvas,useFrame,useThree} from '@react-three/fiber';
import {Environment,Text} from '@react-three/drei';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {LANES as lanes,ASSETS} from '../lib/game/config';
import {AnimatedModel,useOptionalGLTF} from './game/GLBAsset';
import {JUMP_MS,jumpHeight} from '../lib/game/player';
import {detectQuality,qualityConfig} from '../lib/game/performance';


function AssetSlot({url,children,modelProps={},...props}){
 const gltf=useOptionalGLTF(url);
 return <group {...props}>{gltf?<primitive object={gltf.scene.clone(true)} {...modelProps}/>:children}</group>
}
function RunnerAsset({lane,jump,slide,playing,elevated}){
 const gltf=useOptionalGLTF(ASSETS.character);
 const root=useRef(),jumpStart=useRef(0);
 const state=jump?'jump':slide?'slide':playing?'run':'idle';
 useEffect(()=>{if(jump)jumpStart.current=performance.now()},[jump]);
 useFrame((_,d)=>{if(!root.current)return;const progress=jump&&jumpStart.current?Math.min(1,(performance.now()-jumpStart.current)/JUMP_MS):1;const y=(elevated?1.55:0)+(jump?jumpHeight(progress):0);root.current.position.x=THREE.MathUtils.lerp(root.current.position.x,lanes[lane],Math.min(1,d*13));root.current.position.y=THREE.MathUtils.lerp(root.current.position.y,y,Math.min(1,d*18));root.current.rotation.z=THREE.MathUtils.lerp(root.current.rotation.z,(lane-1)*-.08,d*9)});
 if(!gltf)return <AthlRunner lane={lane} jump={jump} slide={slide} elevated={elevated} playing={playing}/>;
 return <group ref={root} position={[0,0,2.55]}><AnimatedModel url={ASSETS.character} state={state} scale={1.1} rotation={[0,Math.PI,0]}/></group>
}

function CameraRig({lane,playing,impact=0,speed=.16}){const{camera}=useThree(),seen=useRef(impact),shake=useRef(0);useEffect(()=>{if(impact!==seen.current){seen.current=impact;shake.current=.18}},[impact]);useFrame(({clock},d)=>{const pace=THREE.MathUtils.clamp((speed-.16)/.18,0,1),bob=playing?Math.sin(clock.elapsedTime*(11+pace*5))*(.022+pace*.018):0,jitter=shake.current>0?(Math.random()-.5)*shake.current:0;shake.current=Math.max(0,shake.current-d*.8);camera.position.x=THREE.MathUtils.lerp(camera.position.x,(lane-1)*(.16+pace*.05)+jitter,d*6);camera.position.y=THREE.MathUtils.lerp(camera.position.y,3.28-pace*.22+bob+Math.abs(jitter)*.25,d*5);camera.position.z=THREE.MathUtils.lerp(camera.position.z,7.35-pace*.38,d*3);const targetFov=54+pace*8;if(Math.abs(camera.fov-targetFov)>.05){camera.fov=THREE.MathUtils.lerp(camera.fov,targetFov,d*3);camera.updateProjectionMatrix()}camera.lookAt(0,.9,-2.8-pace*.6)});return null}
function AthlRunner({lane,jump,slide,playing,elevated}){
 const root=useRef(),leftLeg=useRef(),rightLeg=useRef(),leftArm=useRef(),rightArm=useRef(),scarf=useRef(),jumpStart=useRef(0);
 useEffect(()=>{if(jump)jumpStart.current=performance.now()},[jump]);
 useFrame(({clock},d)=>{if(!root.current)return;const t=clock.elapsedTime*13,run=playing?Math.sin(t):0,progress=jump&&jumpStart.current?Math.min(1,(performance.now()-jumpStart.current)/JUMP_MS):1,y=(elevated?1.55:0)+(jump?jumpHeight(progress):0);root.current.position.x=THREE.MathUtils.lerp(root.current.position.x,lanes[lane],Math.min(1,d*13));root.current.position.y=THREE.MathUtils.lerp(root.current.position.y,y,Math.min(1,d*18));root.current.rotation.z=THREE.MathUtils.lerp(root.current.rotation.z,(lane-1)*-.11,d*8);root.current.rotation.x=THREE.MathUtils.lerp(root.current.rotation.x,playing?-.045:0,d*5);root.current.scale.y=THREE.MathUtils.lerp(root.current.scale.y,slide?.55:1,d*12);if(leftLeg.current)leftLeg.current.rotation.x=run*.62;if(rightLeg.current)rightLeg.current.rotation.x=-run*.62;if(leftArm.current)leftArm.current.rotation.x=-run*.55;if(rightArm.current)rightArm.current.rotation.x=run*.55;if(scarf.current)scarf.current.rotation.z=Math.sin(t*.35)*.08});
 return <group ref={root} position={[0,0,2.55]} scale={1.12}>
   <group ref={leftLeg} position={[-.18,.43,0]}><mesh castShadow position={[0,-.34,0]}><capsuleGeometry args={[.105,.58,7,14]}/><meshStandardMaterial color="#f4f0e8" roughness={.7}/></mesh><mesh castShadow position={[0,-.72,.12]}><boxGeometry args={[.27,.16,.5]}/><meshStandardMaterial color="#47372e"/></mesh></group>
   <group ref={rightLeg} position={[.18,.43,0]}><mesh castShadow position={[0,-.34,0]}><capsuleGeometry args={[.105,.58,7,14]}/><meshStandardMaterial color="#f4f0e8" roughness={.7}/></mesh><mesh castShadow position={[0,-.72,.12]}><boxGeometry args={[.27,.16,.5]}/><meshStandardMaterial color="#47372e"/></mesh></group>
   <mesh castShadow position={[0,1.18,0]}><capsuleGeometry args={[.34,.9,10,20]}/><meshStandardMaterial color="#f5f1e9" roughness={.72}/></mesh>
   <mesh castShadow position={[0,1.17,.24]}><boxGeometry args={[.68,.82,.09]}/><meshStandardMaterial color="#c7a27b" roughness={.9}/></mesh>
   <mesh position={[-.28,1.48,.3]} rotation={[0,0,-.14]}><boxGeometry args={[.075,.76,.05]}/><meshStandardMaterial color="#604536"/></mesh><mesh position={[.28,1.48,.3]} rotation={[0,0,.14]}><boxGeometry args={[.075,.76,.05]}/><meshStandardMaterial color="#604536"/></mesh>
   <Text position={[0,1.2,.3]} fontSize={.13} color="#5c4132">أثل</Text>
   <group ref={leftArm} position={[-.42,1.38,0]} rotation={[0,0,.1]}><mesh castShadow position={[0,-.28,0]}><capsuleGeometry args={[.1,.5,7,14]}/><meshStandardMaterial color="#f5f1e9"/></mesh><mesh position={[0,-.61,.02]}><sphereGeometry args={[.115,16,12]}/><meshStandardMaterial color="#bd815d"/></mesh></group>
   <group ref={rightArm} position={[.42,1.38,0]} rotation={[0,0,-.1]}><mesh castShadow position={[0,-.28,0]}><capsuleGeometry args={[.1,.5,7,14]}/><meshStandardMaterial color="#f5f1e9"/></mesh><mesh position={[0,-.61,.02]}><sphereGeometry args={[.115,16,12]}/><meshStandardMaterial color="#bd815d"/></mesh></group>
   <mesh castShadow position={[0,1.96,0]}><sphereGeometry args={[.36,28,20]}/><meshStandardMaterial color="#c68a65"/></mesh>
   <mesh position={[0,1.98,-.27]}><sphereGeometry args={[.34,20,14]}/><meshStandardMaterial color="#2e211c"/></mesh>
   <group ref={scarf} position={[0,1.86,-.3]}><mesh rotation={[.15,0,0]}><coneGeometry args={[.46,.95,4]}/><meshStandardMaterial color="#b53f35" roughness={.85}/></mesh><mesh position={[0,-.05,-.02]} rotation={[0,0,.78]}><boxGeometry args={[.72,.035,.02]}/><meshStandardMaterial color="#f2e5d8"/></mesh><mesh position={[0,-.28,-.02]} rotation={[0,0,.78]}><boxGeometry args={[.58,.035,.02]}/><meshStandardMaterial color="#f2e5d8"/></mesh></group>
   <mesh castShadow position={[0,2.22,.02]} rotation={[.04,0,0]}><cylinderGeometry args={[.37,.4,.2,28]}/><meshStandardMaterial color="#d8c19f" roughness={.85}/></mesh><mesh position={[0,2.19,.31]} rotation={[.25,0,0]}><boxGeometry args={[.55,.08,.38]}/><meshStandardMaterial color="#604536"/></mesh><Text position={[0,2.24,.2]} fontSize={.1} color="#4f3527">أثل</Text>
 </group>
}

function Palm({x,z,s=1}){return <group position={[x,0,z]} scale={s}><mesh castShadow position={[0,1.15,0]}><cylinderGeometry args={[.1,.18,2.3,8]}/><meshStandardMaterial color="#795236" roughness={1}/></mesh>{[0,1,2,3,4,5,6].map(i=><mesh key={i} position={[0,2.35,0]} rotation={[0,i*Math.PI/3.5,.72]}><boxGeometry args={[.1,.035,1.45]}/><meshStandardMaterial color="#526441" roughness={.9}/></mesh>)}</group>}
function AthlFlag({x,z,flip=false}){return <group position={[x,0,z]}><mesh position={[0,1.65,0]}><cylinderGeometry args={[.025,.035,3.3,7]}/><meshStandardMaterial color="#5b4436" metalness={.3}/></mesh><mesh position={[flip?-.34:.34,2.55,0]}><boxGeometry args={[.68,.62,.025]}/><meshStandardMaterial color="#e7d1ad" roughness={.8}/></mesh><Text position={[flip?-.34:.34,2.55,.018]} fontSize={.13} color="#5a4030">ATHL</Text></group>}
function MarketFront({side,index}){const x=side*4.05,face=-side*.74;return <group position={[x,0,-6]}><mesh castShadow position={[0,1.5,0]}><boxGeometry args={[2.45,3,11]}/><meshStandardMaterial color={index%3===0?'#79513b':index%3===1?'#b47d55':'#946144'} roughness={.92}/></mesh>{[-4,-1.3,1.4,4].map((dz,k)=><group key={k} position={[face,1.55,dz]}><mesh><boxGeometry args={[.08,1.35,1.7]}/><meshStandardMaterial color="#352b26"/></mesh><mesh position={[side*-.05,.88,0]}><boxGeometry args={[.14,.22,1.85]}/><meshStandardMaterial color="#d5b17e"/></mesh>{k%2===0&&<Text position={[side*-.1,.9,0]} rotation={[0,side>0?-Math.PI/2:Math.PI/2,0]} fontSize={.18} color="#f0ddbd">أثل</Text>}</group>)}</group>}
function StreetTile({index}){const z=-index*12;return <group position={[0,0,z]}>
 <mesh receiveShadow position={[0,-.14,-6]}><boxGeometry args={[5.45,.2,12]}/><meshStandardMaterial color="#9f744e" roughness={.96}/></mesh>
 {lanes.map((x,i)=><mesh key={x} receiveShadow position={[x,-.025,-6]}><boxGeometry args={[1.34,.045,12]}/><meshStandardMaterial color={i===1?'#bc8c5d':'#b28257'} roughness={.9}/></mesh>)}
 {[-.74,.74].map(x=><group key={x}>{[1.5,4.5,7.5,10.5].map(k=><mesh key={k} position={[x,.01,-k]}><boxGeometry args={[.035,.018,1.7]}/><meshBasicMaterial color="#ead0a7"/></mesh>)}</group>)}
 <MarketFront side={-1} index={index}/><MarketFront side={1} index={index}/>
 {index%2===0&&<><Palm x={-2.95} z={-2.2} s={.88}/><AthlFlag x={2.82} z={-4.8}/></>}
 {index%2===1&&<><Palm x={3} z={-8.5} s={1}/><AthlFlag x={-2.82} z={-7.1} flip/></>}
 {index%3===0&&<group position={[2.72,.28,-10]}><mesh castShadow><boxGeometry args={[.75,.55,.7]}/><meshStandardMaterial color="#76513b"/></mesh><mesh position={[-.45,-.05,.1]}><boxGeometry args={[.55,.42,.55]}/><meshStandardMaterial color="#c19a6d"/></mesh></group>}
 </group>}
function Mountains(){return <group position={[0,-.2,-30]}>{[-12,-7,-2,3,8,13].map((x,i)=><mesh key={x} position={[x,2.3+(i%2)*.7,0]} rotation={[0,0,i%2?.08:-.06]}><coneGeometry args={[5.8+(i%3),5.8+(i%2),4]}/><meshStandardMaterial color={i%2?'#9f7558':'#87624c'} roughness={1}/></mesh>)}</group>}
function HorizonSign(){return <group position={[0,4.1,-17]}><mesh><boxGeometry args={[6.5,.12,.12]}/><meshStandardMaterial color="#604536"/></mesh><mesh position={[-3.05,-1.2,0]}><boxGeometry args={[.12,2.5,.12]}/><meshStandardMaterial color="#604536"/></mesh><mesh position={[3.05,-1.2,0]}><boxGeometry args={[.12,2.5,.12]}/><meshStandardMaterial color="#604536"/></mesh><mesh position={[0,-.05,.05]}><boxGeometry args={[3.4,.82,.08]}/><meshStandardMaterial color="#ead4b2"/></mesh><Text position={[0,-.04,.1]} fontSize={.3} color="#543a2c">ATHL  •  أثل</Text></group>}
function World({moving,speed=.16}){const root=useRef();useFrame((_,d)=>{if(!root.current||!moving)return;const pace=THREE.MathUtils.clamp((speed-.16)/.18,0,1);root.current.position.z+=d*(7.2+pace*7);if(root.current.position.z>=12)root.current.position.z-=12;});return <><Mountains/><HorizonSign/><group ref={root}>{[0,1,2,3].map(i=><StreetTile key={i} index={i}/>)}</group></>}
function SpeedStreaks({speed=.16,playing=false,quality='medium'}){const root=useRef();useFrame((_,d)=>{if(root.current&&playing)root.current.position.z=(root.current.position.z+d*(12+speed*30))%8});const pace=THREE.MathUtils.clamp((speed-.16)/.18,0,1);if(!playing||pace<.28||quality==='low')return null;return <group ref={root}>{Array.from({length:quality==='high'?14:8},(_,i)=>{const x=((i*1.73)%6)-3,y=.3+((i*1.17)%3),z=-2-((i*2.31)%12);return <mesh key={i} position={[x,y,z]} rotation={[Math.PI/2,0,0]}><cylinderGeometry args={[.008,.018,.55+pace*.8,5]}/><meshBasicMaterial color="#f6dfbd" transparent opacity={.12+pace*.22}/></mesh>})}</group>}

function Item({o}){const x=lanes[o.lane],z=4-o.depth;
 if(o.type==='platform')return <group position={[x,.72,z]}><mesh castShadow><boxGeometry args={[1.32,1.45,5.8]}/><meshStandardMaterial color="#5a4033" metalness={.18} roughness={.5}/></mesh><mesh position={[0,.77,0]}><boxGeometry args={[1.2,.12,5.6]}/><meshStandardMaterial color="#c69c69" roughness={.75}/></mesh><Text position={[0,.15,2.93]} fontSize={.18} color="#ead8bc">أثل</Text></group>;
 if(o.type==='roofCoffee'||o.type==='roofCake'){const cake=o.type==='roofCake';return <group position={[x,2.05,z]}>{cake?<><mesh castShadow><cylinderGeometry args={[.32,.36,.34,24]}/><meshStandardMaterial color="#92533a"/></mesh><mesh position={[0,.2,0]}><cylinderGeometry args={[.32,.32,.08,24]}/><meshStandardMaterial color="#f0dfc7"/></mesh></>:<><pointLight color="#ffd76b" intensity={.7} distance={2}/><mesh castShadow><cylinderGeometry args={[.28,.23,.48,24]}/><meshStandardMaterial color="#ead3ae"/></mesh><mesh position={[0,.26,0]}><cylinderGeometry args={[.23,.23,.03,24]}/><meshStandardMaterial color="#42271a"/></mesh></>}</group>};
 if(o.type==='train')return <group position={[x,1.05,z]}><mesh castShadow><boxGeometry args={[1.3,2.1,3.8]}/><meshStandardMaterial color="#4b3930" metalness={.28} roughness={.48}/></mesh><mesh position={[0,.38,1.93]}><boxGeometry args={[.92,.48,.05]}/><meshStandardMaterial color="#201d1b"/></mesh><mesh position={[-.38,-.55,1.96]}><sphereGeometry args={[.13,16,12]}/><meshStandardMaterial emissive="#ffd47a" emissiveIntensity={2} color="#ffd47a"/></mesh><mesh position={[.38,-.55,1.96]}><sphereGeometry args={[.13,16,12]}/><meshStandardMaterial emissive="#ffd47a" emissiveIntensity={2} color="#ffd47a"/></mesh><Text position={[0,.9,1.96]} fontSize={.2} color="#ead7bb">أثل</Text></group>;
 if(o.type==='highbar')return <group position={[x,0,z]}><mesh castShadow position={[-.52,.9,0]}><boxGeometry args={[.14,1.8,.25]}/><meshStandardMaterial color="#604131"/></mesh><mesh castShadow position={[.52,.9,0]}><boxGeometry args={[.14,1.8,.25]}/><meshStandardMaterial color="#604131"/></mesh><mesh castShadow position={[0,1.48,0]}><boxGeometry args={[1.18,.32,.3]}/><meshStandardMaterial color="#d1a46e"/></mesh><Text position={[0,1.48,.16]} fontSize={.12} color="#52372a">أثل</Text></group>;if(o.type==='barrier')return <group position={[x,.34,z]}><mesh castShadow><boxGeometry args={[1.12,.68,.58]}/><meshStandardMaterial color="#5b3e2d"/></mesh><Text position={[0,.08,.33]} fontSize={.17} color="#ead6b8">أثل</Text></group>;if(o.type==='cake')return <group position={[x,.55,z]}><mesh castShadow><cylinderGeometry args={[.33,.38,.35,28]}/><meshStandardMaterial color="#8d5037"/></mesh><mesh position={[0,.21,0]}><cylinderGeometry args={[.33,.33,.09,28]}/><meshStandardMaterial color="#efe0c8"/></mesh></group>;if(o.type==='bag')return <group position={[x,.62,z]}><mesh castShadow><boxGeometry args={[.6,.92,.22]}/><meshStandardMaterial color="#c5a078"/></mesh><Text position={[0,.04,.12]} fontSize={.15} color="#5b3d2d">أثل</Text></group>;return <group position={[x,.55,z]} rotation={[0,(o.depth||0)*.15,0]}><pointLight color="#ffd76b" intensity={.55} distance={1.8}/><mesh castShadow><cylinderGeometry args={[.3,.24,.52,28]}/><meshStandardMaterial color="#e7cfaa"/></mesh><mesh position={[.31,.04,0]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[.15,.04,12,24]}/><meshStandardMaterial color="#e7cfaa"/></mesh><mesh position={[0,.28,0]}><cylinderGeometry args={[.245,.245,.03,28]}/><meshStandardMaterial color="#3f2519"/></mesh><Text position={[0,.03,.25]} fontSize={.09} color="#563929">أثل</Text></group>}
export default function RunnerScene({lane=1,jump=false,slide=false,elevated=false,objects=[],playing=false,juice=null,impact=0,speed=.16}){
 const[level]=useState(()=>detectQuality()),[visible,setVisible]=useState(true),q=qualityConfig(level);
 useEffect(()=>{const onVisibility=()=>setVisible(!document.hidden);document.addEventListener('visibilitychange',onVisibility);return()=>document.removeEventListener('visibilitychange',onVisibility)},[]);
 return <Canvas shadows={q.shadows} dpr={q.dpr} frameloop={visible?'always':'never'} camera={{position:[0,3.25,7.35],fov:54}} gl={{antialias:q.antialias,toneMapping:THREE.ACESFilmicToneMapping,toneMappingExposure:1.12,powerPreference:'high-performance'}}><color attach="background" args={['#d9b990']}/><fog attach="fog" args={['#d9b990',15,q.far]}/><ambientLight intensity={1.1}/><hemisphereLight intensity={1.1} color="#fff1d6" groundColor="#65442f"/><directionalLight castShadow={q.shadows} shadow-mapSize-width={level==='high'?1024:512} shadow-mapSize-height={level==='high'?1024:512} position={[-4,9,5]} intensity={2.8} color="#ffd7a2"/><AssetSlot url={ASSETS.environment}><World moving={playing&&visible} speed={speed}/></AssetSlot><SpeedStreaks speed={speed} playing={playing&&visible} quality={level}/>{objects.map(o=><Item key={o.id} o={o}/>)}<RunnerAsset lane={lane} jump={jump} slide={slide} elevated={elevated} playing={playing&&visible}/><CameraRig lane={lane} playing={playing&&visible} impact={impact} speed={speed}/>{level!=='low'&&<Environment preset="sunset"/>}</Canvas>
}