'use client';
import {Canvas,useFrame} from '@react-three/fiber';
import {Environment,Text} from '@react-three/drei';
import {useRef} from 'react';
import * as THREE from 'three';
const lanes=[-1.55,0,1.55];
function Runner({lane,jump,slide}){
 const g=useRef(),leg=useRef();
 useFrame(({clock},d)=>{if(!g.current)return;g.current.position.x=THREE.MathUtils.lerp(g.current.position.x,lanes[lane],Math.min(1,d*12));g.current.position.y=THREE.MathUtils.lerp(g.current.position.y,jump?1.25:0,Math.min(1,d*9));g.current.rotation.z=THREE.MathUtils.lerp(g.current.rotation.z,(lane-1)*-.05,d*8);g.current.scale.y=THREE.MathUtils.lerp(g.current.scale.y,slide?.55:1,d*12);if(leg.current)leg.current.rotation.x=Math.sin(clock.elapsedTime*14)*.7});
 return <group ref={g} position={[0,0,2.7]}><mesh castShadow position={[0,.88,0]}><capsuleGeometry args={[.34,.82,8,18]}/><meshStandardMaterial color="#644737"/></mesh><mesh castShadow position={[0,1.62,0]}><sphereGeometry args={[.36,24,18]}/><meshStandardMaterial color="#c99570"/></mesh><mesh position={[0,1.75,-.23]} rotation={[.15,0,0]}><cylinderGeometry args={[.37,.37,.16,24]}/><meshStandardMaterial color="#3b2a21"/></mesh><group ref={leg}><mesh castShadow position={[-.22,.28,0]}><capsuleGeometry args={[.11,.55,6,12]}/><meshStandardMaterial color="#282521"/></mesh><mesh castShadow position={[-.22,-.08,.1]}><boxGeometry args={[.25,.14,.48]}/><meshStandardMaterial color="#efe4d5"/></mesh></group><mesh castShadow position={[.22,.28,0]} rotation={[-.55,0,0]}><capsuleGeometry args={[.11,.55,6,12]}/><meshStandardMaterial color="#282521"/></mesh><mesh position={[0,.95,.34]}><boxGeometry args={[.55,.34,.05]}/><meshStandardMaterial color="#efe1ca"/></mesh><Text position={[0,.95,.38]} fontSize={.14} color="#604536">أثل</Text></group>
}
function World({moving}){
 const stripes=useRef();
 useFrame((_,d)=>{if(stripes.current&&moving){stripes.current.position.z+=d*10;if(stripes.current.position.z>4)stripes.current.position.z=-2}});
 return <><mesh receiveShadow position={[0,-.12,-8]}><boxGeometry args={[5.2,.18,34]}/><meshStandardMaterial color="#a77b50"/></mesh>{[-1.55,0,1.55].map(x=><mesh key={x} position={[x,-.015,-8]}><boxGeometry args={[1.43,.04,34]}/><meshStandardMaterial color="#b88c5d"/></mesh>)}<group ref={stripes}>{[-.78,.78].map(x=><group key={x}>{Array.from({length:10},(_,i)=><mesh key={i} position={[x,.02,-i*3]}><boxGeometry args={[.045,.02,1.35]}/><meshStandardMaterial color="#e2caa3"/></mesh>)}</group>)}</group>{Array.from({length:9},(_,i)=><group key={i}>{[-4.2,4.2].map((x,j)=><group key={j} position={[x,0,-i*4]}><mesh castShadow position={[0,1.8,0]}><boxGeometry args={[2.7,3.6,2.4]}/><meshStandardMaterial color={i%3===0?'#704c36':i%3===1?'#d1a16f':'#8e6548'}/></mesh><mesh position={[j?-.8:.8,2.1,1.22]}><boxGeometry args={[.55,.75,.05]}/><meshStandardMaterial color="#f2c66f"/></mesh></group>)}</group>)}</>
}
function Item({o}){const x=lanes[o.lane],z=4-o.depth;if(o.type==='barrier')return <group position={[x,.55,z]}><mesh castShadow><boxGeometry args={[1.18,1.1,.5]}/><meshStandardMaterial color="#493329"/></mesh><mesh position={[0,.05,.27]}><boxGeometry args={[.88,.23,.04]}/><meshStandardMaterial color="#e6c08d"/></mesh><Text position={[0,.05,.3]} fontSize={.13} color="#543b2d">أثل</Text></group>;if(o.type==='cake')return <group position={[x,.55,z]}><mesh castShadow><cylinderGeometry args={[.32,.37,.34,24]}/><meshStandardMaterial color="#b9784f"/></mesh><mesh position={[0,.2,0]}><cylinderGeometry args={[.32,.32,.09,24]}/><meshStandardMaterial color="#f1dfc5"/></mesh></group>;if(o.type==='bag')return <group position={[x,.62,z]}><mesh castShadow><boxGeometry args={[.58,.9,.2]}/><meshStandardMaterial color="#624332"/></mesh><Text position={[0,.05,.11]} fontSize={.14} color="#f6e5cb">أثل</Text></group>;return <group position={[x,.52,z]}><mesh castShadow><cylinderGeometry args={[.29,.24,.5,24]}/><meshStandardMaterial color="#f4e7d5"/></mesh><mesh position={[.3,.04,0]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[.15,.04,10,20]}/><meshStandardMaterial color="#f4e7d5"/></mesh><mesh position={[0,.27,0]}><cylinderGeometry args={[.24,.24,.025,24]}/><meshStandardMaterial color="#4b2b1d"/></mesh></group>}
export default function RunnerScene({lane=1,jump=false,slide=false,objects=[],playing=false}){return <Canvas shadows dpr={[1,1.5]} camera={{position:[0,3.15,7.5],fov:57}}><color attach="background" args={['#d8bd9d']}/><fog attach="fog" args={['#d8bd9d',14,31]}/><ambientLight intensity={1.35}/><directionalLight castShadow position={[-4,8,5]} intensity={2.3}/><World moving={playing}/>{objects.map(o=><Item key={o.id} o={o}/>)}<Runner lane={lane} jump={jump} slide={slide}/><Environment preset="sunset"/></Canvas>}